This is a small (minimal?) demonstration of an issue when using pytype and protobuf together.

I suspect there's an easy resolution involving... passing the right flags to
pytype so it notices the .pyi files.

See TODO issue report.
